services:
  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - ./pipeline_outputs:/app/pipeline_outputs
      - ./debug_outputs:/app/debug_outputs
      - ./conf/local.pipeline_conf.yaml:/app/conf/local.pipeline_conf.yaml:ro
      - ./fastocr/weight:/app/fastocr/weight:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
